export const JWT_OPTIONS = Symbol('JWT_OPTIONS');
export const PASSWORD_OPTIONS = 'PASSWORD_OPTIONS';
export const PASSWORD_SERVICE = Symbol('PASSWORD_SERVICE');
export const AUTH_LOCAL_SERVICE = Symbol('AUTH_LOCAL_SERVICE');
