version: "3.8"
services:
  monstache:
    image: rwynn/monstache:latest
    command:
      - "-mongo-url"
      - "mongodb://${MONGO_INITDB_ROOT_USERNAME}:${MONGO_INITDB_ROOT_PASSWORD}@mongo1:27017,mongo2:27017,mongo3:27017/?replicaSet=$REPLICA_NAME"
      - "-elasticsearch-url"
      - "http://elasticsearch:9200"
      - "-elasticsearch-user"
      - ${ELASTIC_USERNAME}
      - "-elasticsearch-password"
      - ${ELASTIC_PASSWORD}
      - "-direct-read-namespace" # Change this line
      - "$MONGO_INITDB_DATABASE.$MONGO_INITDB_COLLECTION_NAME"
      - "./config.toml"

    volumes:
      - ./config/config.toml:/config.toml
    ports:
      - 8080:8080
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME:-root}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD:-password}
      MONGO_INITDB_DATABASE_USERNAME: ${MONGO_INITDB_DATABASE_USERNAME:-admin}
      MONGO_INITDB_DATABASE_PASSWORD: ${MONGO_INITDB_DATABASE_PASSWORD:-password}
      MONGO_INITDB_DATABASE: ${MONGO_INITDB_DATABASE:-admin}
      MONGO_INITDB_COLLECTION_NAME: ${MONGO_INITDB_COLLECTION_NAME:-mycollection}
      REPLICA_NAME: ${REPLICA_NAME:-rs0}
      ELASTIC_USERNAME: ${ELASTIC_USERNAME:-elastic}
      ELASTIC_PASSWORD: ${ELASTIC_PASSWORD:-password}

    networks:
      - searchEngines

networks:
  searchEngines:
    name: searchEngines
    external: true
