version: "3.8"

services:
  mongo1:
    image: mongo:latest
    hostname: mongo1
    container_name: mongo1
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME:-root}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD:-password}
      MONGO_INITDB_DATABASE_USERNAME: ${MONGO_INITDB_DATABASE_USERNAME:-admin}
      MONGO_INITDB_DATABASE_PASSWORD: ${MONGO_INITDB_DATABASE_PASSWORD:-password}
      MONGO_INITDB_DATABASE: ${MONGO_INITDB_DATABASE:-admin}
      MONGO_INITDB_COLLECTION_NAME: ${MONGO_INITDB_COLLECTION_NAME:-mycollection}
      REPLICA_NAME: ${REPLICA_NAME:-rs0}
    ports:
      - 27017:27017
    volumes:
      - ./data/db/replica/mongo1:/data/db
      - ./mongodb.key:/etc/mongodb.key
      - ./init-replica.js:/docker-entrypoint-initdb.d/init-replica.js
      - ./init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js
    command:
      - "--replSet"
      - ${REPLICA_NAME}
      - "--keyFile"
      - "/etc/mongodb.key"
      - "--bind_ip_all"
    networks:
      - searchEngines

  mongo2:
    image: mongo:latest
    hostname: mongo2
    container_name: mongo2
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME:-root}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD:-password}
      MONGO_INITDB_DATABASE_USERNAME: ${MONGO_INITDB_DATABASE_USERNAME:-admin}
      MONGO_INITDB_DATABASE_PASSWORD: ${MONGO_INITDB_DATABASE_PASSWORD:-password}
      MONGO_INITDB_DATABASE: ${MONGO_INITDB_DATABASE:-admin}
      MONGO_INITDB_COLLECTION_NAME: ${MONGO_INITDB_COLLECTION_NAME:-mycollection}
      REPLICA_NAME: ${REPLICA_NAME:-rs0}
    ports:
      - 27018:27017
    volumes:
      - ./data/db/replica/mongo2:/data/db
      - ./mongodb.key:/etc/mongodb.key
    command:
      - "--replSet"
      - ${REPLICA_NAME}
      - "--keyFile"
      - "/etc/mongodb.key"
      - "--bind_ip_all"
    networks:
      - searchEngines

  mongo3:
    image: mongo:latest
    hostname: mongo3
    container_name: mongo3
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME:-root}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD:-password}
      MONGO_INITDB_DATABASE_USERNAME: ${MONGO_INITDB_DATABASE_USERNAME:-admin}
      MONGO_INITDB_DATABASE_PASSWORD: ${MONGO_INITDB_DATABASE_PASSWORD:-password}
      MONGO_INITDB_DATABASE: ${MONGO_INITDB_DATABASE:-admin}
      MONGO_INITDB_COLLECTION_NAME: ${MONGO_INITDB_COLLECTION_NAME:-mycollection}
      REPLICA_NAME: ${REPLICA_NAME:-rs0}
    ports:
      - 27019:27017
    volumes:
      - ./data/db/replica/mongo3:/data/db
      - ./mongodb.key:/etc/mongodb.key
    command:
      - "--replSet"
      - ${REPLICA_NAME}
      - "--keyFile"
      - "/etc/mongodb.key"
      - "--bind_ip_all"
    networks:
      - searchEngines

  setReplica:
    image: mongo:latest
    depends_on:
      - mongo1
      - mongo2
      - mongo3
    volumes:
      - ./init-replica.js:/docker-entrypoint-initdb.d/init-replica.js
      - ./init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js
    entrypoint: ["/bin/sh", "-c"]
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME:-root}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD:-password}
      MONGO_INITDB_DATABASE_USERNAME: ${MONGO_INITDB_DATABASE_USERNAME:-admin}
      MONGO_INITDB_DATABASE_PASSWORD: ${MONGO_INITDB_DATABASE_PASSWORD:-password}
      MONGO_INITDB_DATABASE: ${MONGO_INITDB_DATABASE:-admin}
      MONGO_INITDB_COLLECTION_NAME: ${MONGO_INITDB_COLLECTION_NAME:-mycollection}
      REPLICA_NAME: ${REPLICA_NAME:-rs0}
    command:
      - |
        sleep 20 &&
        mongosh --host mongo1:27017 -u ${MONGO_INITDB_ROOT_USERNAME:-root} -p ${MONGO_INITDB_ROOT_PASSWORD:-password} --authenticationDatabase admin /docker-entrypoint-initdb.d/init-replica.js &&
        /docker-entrypoint-initdb.d/init-mongo.js
    networks:
      - searchEngines
networks:
  searchEngines:
    name: searchEngines
    external: true
