name: push-main
on:
  push:
    branches:
      - main

jobs:
  test:
    uses: Hoit-me/action/.github/workflows/test.yml@main
    with:
      node-version: '20.5.1'
      pnpm-version: '8'

  build:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - uses: actions/checkout@v3
      - name: env
        run: |
          echo "API_KEY=$API_KEY" >> .env
          echo "API_KEY_DECODED=$API_KEY_DECODED" >> .env
          echo "AWS_REGION=$AWS_REGION" >> .env
          echo "AWS_S3_BUCKET=$AWS_S3_BUCKET" >> .env
          echo "DATABASE_URL=$DATABASE_URL" >> .env
          echo "S3_AWS_ACCESS_KEY_ID=$S3_AWS_ACCESS_KEY_ID" >> .env
          echo "S3_AWS_SECRET_ACCESS_KEY=$S3_AWS_SECRET_ACCESS_KEY" >> .env
          echo "REDIS_URL=$REDIS_URL" >> .env
        env:
          API_KEY: ${{ secrets.API_KEY }}
          API_KEY_DECODED: ${{ secrets.API_KEY_DECODED }}
          AWS_REGION: ${{ secrets.AWS_REGION }}
          AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
          S3_AWS_ACCESS_KEY_ID: ${{ secrets.S3_AWS_ACCESS_KEY_ID }}
          S3_AWS_SECRET_ACCESS_KEY: ${{ secrets.S3_AWS_SECRET_ACCESS_KEY }}
          REDIS_URL: ${{ secrets.REDIS_URL }}

      - name: docker build
        run: |
          docker build -t ${{ secrets.AWS_ECR }}:latest .

      - name: aws login
        run: |
          aws configure set aws_access_key_id ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws configure set aws_secret_access_key ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws configure set default.region ap-northeast-2
          aws configure set default.output json

      - name: aws ecr push
        run: |
          aws ecr get-login-password --region ap-northeast-2 | docker login --username AWS --password-stdin ${{ secrets.AWS_ECR }}
          docker tag ${{ secrets.AWS_ECR }}:latest ${{ secrets.AWS_ECR }}:latest
          docker push ${{ secrets.AWS_ECR }}:latest

      - name: aws ecs update
        run: |
          aws ecs update-service --cluster ${{ secrets.AWS_ECS_CLUSTER }} --service ${{ secrets.AWS_ECS_SERVICE }} --force-new-deployment
